version: '{build}'
image: Visual Studio 2019
branches:
  only:
  - master
build_script:
- ps: .\nuget-pack\pack.ps1
test: off
artifacts:  
- path: .\nuget-pack\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: "0ONhNz25ADr6T9tsAYmv/My8usEPJSxofq4ITyMfcc/ttxo0psu/HF7zdQQr7iyU"
  skip_symbols: true
  on:
    branch: master