//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRegistry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceEnvironment
    {
        public ServiceEnvironment()
        {
            this.ServiceMapping = new HashSet<ServiceMapping>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<ServiceMapping> ServiceMapping { get; set; }
    }
}
