//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRegistry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceMapping
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public string Namespace { get; set; }
        public string Environment { get; set; }
        public string Address { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ServiceEnvironment ServiceEnvironment { get; set; }
    }
}
